### PR TITLE
Add prose lint as a first linter.

### PR DESCRIPTION
**Pull request by dedan**
Use the javascript wrapper that strips out markdown code and has a nicer reporter.

+@pcorpet

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-lint/1)

### CODE REVIEW

**Comment by pcorpet** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 3 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-KcwzscGlHISH7ojpXxo:-KcwzscGlHISH7ojpXxp:bk1hiyf) ([raw file](https://github.com/bayesimpact/docker-lint/blob/2249287ad9d471719f2017135c1ab6db617865dc/README.md#L3)):*
> ```Markdown
> # Linter Container
> 
> Several linters packaged into a handy container.
> ```

It says several, so please add a TODO to add more.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-KcwzvvHhjuwoCFNCYCc:-KcwzvvIsntaJW3FCC30:b6grwzx) ([raw file](https://github.com/bayesimpact/docker-lint/blob/2249287ad9d471719f2017135c1ab6db617865dc/README.md#L8)):*
> ```Markdown
> [bayesimpact/docker-lint](https://hub.docker.com/r/bayesimpact/docker-lint/).
> 
> [](https://hub.docker.com/r/bayesimpact/docker-lint/)
> ```

Please comment on how one should use this docker (probably a command line).

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-Kcx-1mn6QaxdOZRAdEd:-Kcx-1mn6QaxdOZRAdEe:bqp3i9p) ([raw file](https://github.com/bayesimpact/docker-lint/blob/2249287ad9d471719f2017135c1ab6db617865dc/README.md#L9)):*
> ```Markdown
> 
> [](https://hub.docker.com/r/bayesimpact/docker-lint/)
> ```

Add a § on alternatives and why you've decided to create a new one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1)*

**Comment by dedan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 3 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-KcwzscGlHISH7ojpXxo:-Kcx0DssS-ttmGPoDUTB:b-896fix) ([raw file](https://github.com/bayesimpact/docker-lint/blob/2249287ad9d471719f2017135c1ab6db617865dc/README.md#L3)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

It says several, so please add a TODO to add more.
</blockquote></details>

Done.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-KcwzvvHhjuwoCFNCYCc:-Kcx4BMXAkVQcQpFpRlO:b-896fix) ([raw file](https://github.com/bayesimpact/docker-lint/blob/2249287ad9d471719f2017135c1ab6db617865dc/README.md#L8)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please comment on how one should use this docker (probably a command line).
</blockquote></details>

Done.

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-Kcx-1mn6QaxdOZRAdEd:-Kcx4BnZ4ZqmiFlE3jzg:b-896fix) ([raw file](https://github.com/bayesimpact/docker-lint/blob/2249287ad9d471719f2017135c1ab6db617865dc/README.md#L9)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Add a § on alternatives and why you've decided to create a new one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 15 at r2](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-KcxGc-Qx72L8ozsi-mP:-KcxGc-Qx72L8ozsi-mQ:b-qdrphi) ([raw file](https://github.com/bayesimpact/docker-lint/blob/5ec9297bdaa61490a041050bafad6d75449a579f/README.md#L15)):*
> ```Markdown
> Mount the code to be linted into the container and run one of the linters from the commandline.
> 
> Example `docker-compose.yml`:
> ```

Can you also give a `docker` command directly please?
`docker run --rm -v $(pwd):/usr/app:ro -v $(pwd)/.proselintrc:/root/.proselintrc:ro bayesimpact/docker-lint proselintjs \*.md`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-:-KcxH3gs-YCVQbxgG1iT:bnfp4nl)*

**Comment by dedan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 15 at r2](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1#-KcxGc-Qx72L8ozsi-mP:-KcxIM_wW7BU4gkQwig-:b-896fix) ([raw file](https://github.com/bayesimpact/docker-lint/blob/5ec9297bdaa61490a041050bafad6d75449a579f/README.md#L15)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Can you also give a `docker` command directly please?
`docker run --rm -v $(pwd):/usr/app:ro -v $(pwd)/.proselintrc:/root/.proselintrc:ro bayesimpact/docker-lint proselintjs \*.md`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-lint/1)*

**Pull request merged**
